# Publish all joints state
/two_link_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # Position Controllers
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 1.0, d: 1.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 1.0, d: 1.0}
